main: main.cpp Bruch.h Bruch.o Complex.h Complex.o 
	c++ -o main main.cpp Bruch.o Complex.o -std=c++11
Bruch.o: Bruch.cpp
	c++ -c Bruch.cpp -std=c++11

Complex.o: Complex.cpp
	c++ -c Complex.cpp -std=c++11


